let techKaro = {
    name: "Tech Karo",
    fees: 500,
    courseName: ["Web Development", "Life Skills"],
    duration: 8,
    schedule: {
        time: "from 2PM to 6PM",
        inWeek: ["tuesday", "thursday", "saturday"],
        lastBatch: "50 graduates",
        courseOutLines: [{
            html: "1 month",
            css: "2 months",
            javascript: "3 months",
            reactWordpress: "3 monthes"
        }],
        certification: [{
                name: "freecodecamp",
                course: ["responsive web designing", "java script", "react"]
            },
            {
                name: "Tech Karo",
                course: "Web Developement"
            }
        ],
    },
    mentorMeetup: {
        meetupTime: "last week of every month",
    },
    staff: [{
            name: "Sadaffe Abid",
            position: "Founder Circle",
            qualification: "Masters",
            about: "women empowerment scheme",
            twitterAccount: "@SadaffeAbid"
        },
        {
            name: "Mashood Rasteger",
            position: "Technical Advisor"
        },
        {
            name: "Sarah Ahmad",
            position: "Lead Instructor",
            qualification: "Masters in software engeneraing",
            about: "Lead Instructer of Tech Karo both batches",
            email: "sarah@gmail.com",
            phone: "03026677890",
            github: "github.com/sarahsga",
            skills: ["web designer", "free lancer", "made andriod Apps"]
        },
        {
            name: "Tuba Mohsin",
            position: "Project Manager",
            qualification: "Masters in software engeneraing",
            about: "Project menagement of tech karo",
            email: "tubamohsin@gmail.com",
            phone: "034398765677",
            skills: ["wed designer", "employ at companey"]
        }
    ],

    techNinjaName: [{
            name: "Rabia Aziz",
            position: "tech ninja",
            email: "rabiaaziz@gmail.com",
            batch: "2019",
            dutyWithGroup: "B"
        },
        {
            name: "Abeera",
            position: "tech ninja",
            email: "abeera@gmail.com",
            batch: "2019",
            dutyWithGroup: "A"
        },
        {
            name: "Waqar",
            position: "tech ninja",
            email: "waqar@gmail.com",
            batch: "2019",
            dutyWithGroup: "B"
        },
        {
            name: "Alli",
            position: "tech ninja",
            email: "alikhan@gmail.com",
            batch: "2019",
            dutyWithGroup: "B"
        },
        {
            name: "Noreen",
            position: "tech ninja",
            email: "noreen@gmail.com",
            batch: "2019",
            dutyWithGroup: "A"
        },
        {
            name: "Arsala",
            position: "tech ninja",
            email: "arsala22@gmail.com",
            batch: "2019",
            dutyWithGroup: "A"
        },
        {
            name: "Khair U Nissa",
            position: "tech ninja",
            email: "khaiunissa@gmail.com",
            batch: "2019",
            dutyWithGroup: "B"
        }
    ],
    venue: "UIT",
    sponsers: [{
            name: "Engro",
            contribution: "donation for students",
            fecelitation: ["notebooks", "prizes"],
            websiteUrl: "https://engro.com.org"
        },
        {
            name: "Caream",
            contribution: " pick and drop",
            fecelitation: "providing promo code",
            websiteUrl: "https://caream.com"
        },
        {
            name: "Sasta Ticket",
            contribution: "donation for students",
            fecelitation: "job opportunities",
            website: "https://sastaticket.com "
        }
    ],
    expenses: ["UIT Rent", "electricity Bills", "Eid Party"],
    internetSources: [{
        websiteUrl: "https://techkaro.com.pk",
        classResourcesURL: "https://classresources",
        slackURL: "https://slack-tk-2019"
    }],
    howManyBatches: ["2018", "2019"],
    rewardList: [{
        prize: ["laptops", "calenders", "tech karo stickers"],
        providing: "job opportunities"
    }],
    successStories: [{
            studentName: "Aniqa",
            batch: "2018",
            gender: "female",
            currentlyWorking: "Engro",
            feedback: "hard work and devotion can make us succeed!",
            salary: 20000,
            skills: ["coding", "web designing"],
        },
        {
            studentName: "Maryam",
            batch: "2018",
            gender: "female",
            currentlyWorking: "Sesta Ticket",
            feedback: "We should believe in ourselves that we can do anything we want!",
            salary: 30000,
            skills: ["web development", "Making andriod Apps", "freelancing"]
        },
        {
            studentName: "Rabia",
            batch: "2018",
            gender: "female",
            currentlyWorking: "Tech Karo",
            feedback: "coding is fun",
            salary: 15000,
            skills: ["web designing", "embasader"],
        }
    ],

    classRooms: [{
            RoomNum: "CL 1",
            group: "A & B"
        },
        {
            RoomNum: "CL 4",
            group: "A"
        },
        {
            RoomNum: "CL 2",
            group: "B"
        }
    ],
    courseDestribution: [{
            saturday: "life Skills"
        },
        {
            webDev: ["Tuesday", "Thursday"]
        },
        {
            uiDesigning: "2 days"
        }
    ],
    lifeSkills: [{
        topic: "Communication",
        reason: "For the guidance of student"
    }],
    differentSessions: [{
            sessionName: "Attitude Skill"
        },
        {
            sessionName: "CV Writing"
        }
    ],
    Groups: [{
            name: "A",
            students: 50
        },
        {
            name: "B",
            students: 60
        }
    ],
    studentsGroupA: [{
            name: "Akbar",
            education: "BA",
            gender: "Male",
            address: "Karachi",
            dob: "23 March 1992",
            cnic: "12702-2348456-3",
            contect: "03458765454",
            maritalStatus: "single",
            github: "github.com/akbar",
            email: "akbar121@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at NED university",
            profession: ["student", "coding"],
            practicHours: 12
        },
        {
            name: "Aniqua",
            education: "MA Economic",
            gender: "female",
            address: "Karachi",
            dob: "27 july 1990",
            cnic: "23703-3847287-8",
            contect: "03034858557",
            maritalStatus: "married",
            github: "github.com/aniqa",
            email: "aniqa222@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "teacher at private school",
            profession: "teacher",
            practicHours: 20
        },


        {
            name: "Ali Raza",
            education: "BA",
            gender: "Male",
            address: "Karachi",
            dob: "10 April 1996",
            cnic: 17203 - 3748765 - 3,
            contect: "03337654332",
            maritalStatus: "single",
            github: "github.com/aliraza",
            email: "aliraza111@gmail.com",
            group: "A",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at University of Karachi",
            profession: "student",
            practicHours: 22
        },


        {
            name: "Alinaa",
            education: "MA English",
            gender: "female",
            address: "Karachi",
            dob: "01 May 1993",
            cnic: 21302 - 2345834 - 8,
            contect: "03359876567",
            maritalStatus: "single",
            github: "github.com/alinaa",
            email: "alinaa@gmail.com",
            group: "A",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at University",
            profession: "sudent",
            practicHours: 12
        },


        {
            name: "Areeba",
            education: "FA",
            gender: "female",
            address: "Karachi",
            dob: "15 June 2000",
            cnic: 17204 - 34567654 - 8,
            contect: "03173434756",
            maritalStatus: "single",
            github: "github.com/areebaa",
            email: "@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: false,
            about: "Teaching at a private sector school",
            profession: "Teacher",
            practicHours: 23
        },


        {
            name: "Bushra",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "30 July 1997",
            cnic: 21309 - 34567654 - 8,
            contect: "03043434489",
            maritalStatus: "single",
            github: "github.com/",
            email: "@gmail.com",
            group: "A",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University ",
            profession: "student",
            practicHours: 14
        },


        {
            name: "Fahmeen",
            education: "MBA",
            gender: "female",
            address: "Karachi",
            dob: "13 August 1997",
            cnic: 42804 - 34567654 - 8,
            contect: "03333434777",
            maritalStatus: "single",
            github: "github.com/fahmeen",
            email: "fahmeen11@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study in academy",
            profession: "student",
            practicHours: 13
        },


        {
            name: "Humera",
            education: "BA",
            gender: "female",
            address: "Karachi",
            dob: "12 March 1997",
            cnic: 21506 - 34567654 - 8,
            contect: "03453434336",
            maritalStatus: "single",
            github: "github.com/humairaa",
            email: "humaira@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "learn coding at academy",
            profession: "freelancer",
            practicHours: 23
        },
        {
            name: "Altaf",
            education: "MA",
            gender: "Male",
            address: "Karachi",
            dob: "01 March 1996",
            cnic: "12702-2348456-3",
            contect: "03178765452",
            maritalStatus: "single",
            github: "github.com/altaf",
            email: "altafkhan@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at  university",
            profession: ["student", "coding"],
            practicHours: 17
        },

        {
            name: "Amna",
            education: "MA English",
            gender: "female",
            address: "Karachi",
            dob: "21 july 1997",
            cnic: "21603-3847287-8",
            contect: "03034858557",
            maritalStatus: "Un married",
            github: "github.com/amina",
            email: "amnaa@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University",
            profession: "student",
            practicHours: 10
        },

        {
            name: "Arif",
            education: "BA",
            gender: "Male",
            address: "Karachi",
            dob: "25 August 1996",
            cnic: 12101 - 3748765 - 3,
            contect: "03457654322",
            maritalStatus: "single",
            github: "github.com/arif",
            email: "arif@gmail.com",
            group: "A",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at University of Karachi",
            profession: "student",
            practicHours: 22
        },


        {
            name: "Samreen",
            education: "MA English",
            gender: "female",
            address: "Karachi",
            dob: "08 May 1997",
            cnic: 21604 - 2345834 - 8,
            contect: "03329876563",
            maritalStatus: "single",
            github: "github.com/samreen",
            email: "samreen@gmail.com",
            group: "A",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at University",
            profession: "sudent",
            practicHours: 12
        },


        {
            name: "Halima",
            education: "FA",
            gender: "female",
            address: "Karachi",
            dob: "10 july 2000",
            cnic: 12104 - 34567654 - 8,
            contect: "03163434711",
            maritalStatus: "single",
            github: "github.com/halima",
            email: "@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: false,
            about: "Study at college",
            profession: "Student",
            practicHours: 15
        },


        {
            name: "Sana",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "30 November 1996",
            cnic: 21306 - 34565654 - 8,
            contect: "03063434484",
            maritalStatus: "single",
            github: "github.com/sana",
            email: "sanaa@gmail.com",
            group: "A",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University ",
            profession: "student",
            practicHours: 14
        },


        {
            name: "Sufia Choudhry",
            education: "MBA",
            gender: "female",
            address: "Karachi",
            dob: "11 August 1998",
            cnic: 21302 - 34567654 - 8,
            contect: "03353434666",
            maritalStatus: "single",
            github: "github.com/sufoia",
            email: "chodhrysofia@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study in academy",
            profession: "student",
            practicHours: 13
        },


        {
            name: "Nazia",
            education: "BA",
            gender: "female",
            address: "Karachi",
            dob: "18 April 1997",
            cnic: 12108 - 34567654 - 8,
            contect: "03463434333",
            maritalStatus: "single",
            github: "github.com/nazia",
            email: "nazia@gmail.com",
            group: "A",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "learn coding at academy",
            profession: "student",
            practicHours: 20
        }

    ],

    studentsGroupB: [{
            name: "Aster Naz",
            education: "BA",
            gender: "female",
            address: "Karachi",
            dob: "12 December 1998",
            cnic: 13402 - 34567654 - 8,
            contect: "03163434704",
            maritalStatus: "single",
            github: "github.com/aster-naz",
            email: "asternaz@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: false,
            about: "study at college",
            profession: "student",
            practicHours: 10
        },
        {
            name: "Armia",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "25 September 1996",
            cnic: 21304 - 34567654 - 8,
            contect: "03013434752",
            maritalStatus: "married",
            github: "github.com/",
            email: "@gmail.com",
            group: "B",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Learning web designing online",
            profession: "Teacher",
            practicHours: 22
        },
        {
            name: "Marzia",
            education: "BA",
            gender: "female",
            address: "Karachi",
            dob: "17 May 1997",
            cnic: 12213 - 34567654 - 8,
            contect: "03123434756",
            maritalStatus: "single",
            github: "github.com/marzia",
            email: "@gmail.com",
            group: "B",
            attendance: false,
            progress: "normal",
            hasComputer: true,
            hasInternet: false,
            hsdSmartPhone: true,
            about: "Study at College",
            profession: "student",
            practicHours: 9
        },
        {
            name: "Raiba Arshad",
            education: "MA Education",
            gender: "female",
            address: "Karachi",
            dob: "06 April 1996",
            cnic: 12101 - 34567654 - 8,
            contect: "03003434754",
            maritalStatus: "single",
            github: "github.com/raiba-arshad",
            email: "raiba@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "Student",
            practicHours: 15
        },
        {
            name: "Somia",
            education: "MA education",
            gender: "female",
            address: "Karachi",
            dob: "02 November 1997",
            cnic: 21702 - 34567654 - 8,
            contect: "03333434755",
            maritalStatus: "single",
            github: "github.com/somia",
            email: "@gmail.com",
            group: "B",
            attendance: true,
            progress: "excellent",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "Student",
            practicHours: 24
        },
        {
            name: "Syeda Humaira",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "04 july 1996",
            cnic: 52178 - 34567654 - 8,
            contect: "03473434758",
            maritalStatus: "married",
            github: "github.com/",
            email: "@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Hous wife",
            profession: "freelancer",
            practicHours: 10
        },
        {
            name: "Talat",
            education: "MA",
            gender: "Male",
            address: "Karachi",
            dob: "26 March 1997",
            cnic: 21703 - 34567654 - 3,
            contect: "03163434752",
            maritalStatus: "married",
            github: "github.com/talat",
            email: "talatk@gmail.com",
            group: "B",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study as a private student",
            profession: "employment in companey",
            practicHours: 12
        },
        {
            name: "Fatima",
            education: "BA",
            gender: "female",
            address: "Karachi",
            dob: "12 December 1998",
            cnic: 13402 - 34567654 - 8,
            contect: "03163434704",
            maritalStatus: "single",
            github: "github.com/aster-naz",
            email: "asternaz@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: false,
            about: "study at college",
            profession: "student",
            practicHours: 10
        },
        {
            name: "Hiraa",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "25 September 1996",
            cnic: 21304 - 34567654 - 8,
            contect: "03013434752",
            maritalStatus: "married",
            github: "github.com/armia",
            email: "armia1112@gmail.com",
            group: "B",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Learning web designing online",
            profession: "Teacher",
            practicHours: 22
        },
        {
            name: "Kokab",
            education: "BA",
            gender: "female",
            address: "Karachi",
            dob: "17 May 1997",
            cnic: 12213 - 34567654 - 8,
            contect: "03123434756",
            maritalStatus: "single",
            github: "github.com/marzia",
            email: "@gmail.com",
            group: "B",
            attendance: false,
            progress: "normal",
            hasComputer: true,
            hasInternet: false,
            hsdSmartPhone: true,
            about: "Study at College",
            profession: "student",
            practicHours: 9
        },
        {
            name: "Mahnoor",
            education: "MA Education",
            gender: "female",
            address: "Karachi",
            dob: "06 April 1996",
            cnic: 12101 - 34567654 - 8,
            contect: "03003434754",
            maritalStatus: "single",
            github: "github.com/raiba-arshad",
            email: "raiba@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "Student",
            practicHours: 15
        },
        {
            name: "Maria",
            education: "MA education",
            gender: "female",
            address: "Karachi",
            dob: "02 November 1997",
            cnic: 21702 - 34567654 - 8,
            contect: "03333434755",
            maritalStatus: "single",
            github: "github.com/somia",
            email: "@gmail.com",
            group: "B",
            attendance: true,
            progress: "excellent",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "Student",
            practicHours: 24
        },
        {
            name: "Muhammad Arshad",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "04 july 1996",
            cnic: 52178 - 34567654 - 3,
            contect: "03473434758",
            maritalStatus: "married",
            github: "github.com/",
            email: "@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Hous wife",
            profession: "freelancer",
            practicHours: 10
        },
        {
            name: "Muhammad Ahsan",
            education: "MA",
            gender: "Male",
            address: "Karachi",
            dob: "26 March 1997",
            cnic: 21703 - 34567654 - 3,
            contect: "03163434752",
            maritalStatus: "married",
            github: "github.com/talat",
            email: "talatk@gmail.com",
            group: "B",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study as a private student",
            profession: "employment in companey",
            practicHours: 12
        },
        {
            name: "Sahrish",
            education: "FA",
            gender: "female",
            address: "Karachi",
            dob: "07 July 2001",
            cnic: 32403 - 34567654 - 8,
            contect: "03433434754",
            maritalStatus: "single",
            github: "github.com/uzmaa",
            email: "uzma123@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: false,
            about: "Study at college",
            profession: "student",
            practicHours: 10
        },
        {
            name: "Sara Riaz",
            education: "MA Education",
            gender: "female",
            address: "Karachi",
            dob: "19 December 1996",
            cnic: 12702 - 34567654 - 8,
            contect: "03323434702",
            maritalStatus: "single",
            github: "github.com/sara-riaz",
            email: "sarariaz@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "study at University of Karachi",
            profession: "student",
            practicHours: 15
        },
        {
            name: "Khadija",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "20 Octuber 1995",
            cnic: 21602 - 34567654 - 8,
            contect: "03062434732",
            maritalStatus: "Un married",
            github: "github.com/khadija",
            email: "khadija@gmail.com",
            group: "B",
            attendance: true,
            progress: "very good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Learning web designing",
            profession: "Teacher",
            practicHours: 22
        },
        {
            name: "Reena Bano",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "18 March 1997",
            cnic: 12211 - 34567654 - 8,
            contect: "03113434755",
            maritalStatus: "single",
            github: "github.com/reenabano",
            email: "reenabano@gmail.com",
            group: "B",
            attendance: false,
            progress: "normal",
            hasComputer: true,
            hasInternet: false,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "student",
            practicHours: 16
        },
        {
            name: "Safina",
            education: "MA Education",
            gender: "female",
            address: "Karachi",
            dob: "06 April 1996",
            cnic: 12101 - 34567654 - 8,
            contect: "03003434754",
            maritalStatus: "single",
            github: "github.com/safina-younes",
            email: "safina@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "Student",
            practicHours: 15
        },
        {
            name: "Bazlah",
            education: "MA education",
            gender: "female",
            address: "Karachi",
            dob: "12 December 1995",
            cnic: 21202 - 34567654 - 8,
            contect: "03353434711",
            maritalStatus: "single",
            github: "github.com/bazlah",
            email: "bazlah@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Study at University of Karachi",
            profession: "Student",
            practicHours: 22
        },
        {
            name: "Ramsha",
            education: "MA",
            gender: "female",
            address: "Karachi",
            dob: "04 March 1996",
            cnic: 13104 - 34567654 - 8,
            contect: "03483434722",
            maritalStatus: " Un married",
            github: "github.com/ramsha",
            email: "ramshaa@gmail.com",
            group: "B",
            attendance: true,
            progress: "good",
            hasComputer: true,
            hasInternet: true,
            hsdSmartPhone: true,
            about: "Teaching",
            profession: "Teacher",
            practicHours: 14
        }
    ]
};